import type { Metadata } from "next";
import "./globals.css";
import '@aws-amplify/ui-react/styles.css';
import ConfigureAmplify from "@/src/utils/configureAmplify";
import { AuthProvider } from "../utils/contexts/AuthContext";

console.log('[APP LAYOUT] Promptopia Loading...');

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // icons: {
  //   icon: '/favicon.ico', // Path to your custom favicon (optional)
  // },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased h-screen flex flex-col px-6`}> 
        <AuthProvider>
          <ConfigureAmplify />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
